// src/renderer/src/components/artifacts/CodeArtifact.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react'
import { Icon } from '@iconify/react'
import { createDeviceClient } from '@api/DeviceClient'
import { useArtifactStore } from '@/stores/artifact'
import { useUiSettingsStore } from '@/stores/uiSettingsStore'
import { detectLanguage, useMonaco } from 'stream-monaco'
import { nanoid } from 'nanoid'

interface CodeArtifactProps {
  block: {
    artifact: { type: string; title: string; language?: string }
    content: string
  }
  isPreview: boolean
  messageId?: string
  threadId?: string
  className?: string
}

function getLanguageIcon(language: string): string {
  const icons: Record<string, string> = {
    javascript: 'logos:javascript',
    typescript: 'logos:typescript-icon',
    python: 'logos:python',
    html: 'logos:html-5',
    css: 'logos:css-3',
    json: 'codicon:json',
    markdown: 'codicon:markdown',
    java: 'logos:java',
    cpp: 'logos:c-plusplus',
    csharp: 'logos:c-sharp',
    go: 'logos:go',
    rust: 'logos:rust',
    sql: 'codicon:database',
    shell: 'codicon:terminal',
    yaml: 'codicon:settings',
    xml: 'codicon:code',
    vue: 'logos:vue',
    react: 'logos:react',
    svelte: 'logos:svelte-icon'
  }
  return icons[language] || 'codicon:file-code'
}

const sanitizeLanguage = (language?: string | null) => {
  if (!language) return ''
  const normalized = language.trim().toLowerCase()
  switch (normalized) {
    case 'md':
      return 'markdown'
    case 'plain':
    case 'text':
      return 'plaintext'
    case 'htm':
      return 'html'
    default:
      return normalized
  }
}

const DISPLAY_NAMES: Record<string, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  java: 'Java',
  cpp: 'C++',
  csharp: 'C#',
  php: 'PHP',
  ruby: 'Ruby',
  go: 'Go',
  rust: 'Rust',
  swift: 'Swift',
  kotlin: 'Kotlin',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  sql: 'SQL',
  json: 'JSON',
  yaml: 'YAML',
  markdown: 'Markdown',
  bash: 'Bash',
  shell: 'Shell',
  powershell: 'PowerShell',
  dockerfile: 'Dockerfile',
  vue: 'Vue',
  react: 'React',
  xml: 'XML',
  svg: 'SVG',
  mermaid: 'Mermaid',
  text: 'Plain Text',
  '': 'Plain Text'
}

export function CodeArtifact({
  block,
  isPreview,
  messageId,
  threadId,
  className
}: CodeArtifactProps) {
  const deviceClient = createDeviceClient()
  const uiSettingsStore = useUiSettingsStore()
  const artifactStore = useArtifactStore()
  const codeEditorRef = useRef<HTMLDivElement>(null)
  const [copyText, setCopyText] = useState('Copy')
  const [codeLanguage, setCodeLanguage] = useState(() => sanitizeLanguage(block.artifact?.language))
  const lastThrottleRef = useRef(0)

  const { createEditor, updateCode, getEditorView } = useMonaco({
    wordWrap: 'on',
    wrappingIndent: 'same',
    fontFamily: uiSettingsStore.formattedCodeFontFamily
  })

  const throttledDetectLanguage = (code: string) => {
    const now = Date.now()
    if (now - lastThrottleRef.current < 1000) return
    lastThrottleRef.current = now
    setCodeLanguage(sanitizeLanguage(detectLanguage(code)))
  }

  useEffect(() => {
    if (!codeLanguage || codeLanguage === '') {
      throttledDetectLanguage(block.content)
    }
  }, [])

  const isMermaid = useMemo(() => codeLanguage === 'mermaid', [codeLanguage])
  const isPreviewable = useMemo(
    () => codeLanguage === 'html' || codeLanguage === 'svg',
    [codeLanguage]
  )
  const languageIcon = useMemo(() => getLanguageIcon(codeLanguage), [codeLanguage])
  const displayLanguage = useMemo(
    () =>
      DISPLAY_NAMES[codeLanguage] || codeLanguage.charAt(0).toUpperCase() + codeLanguage.slice(1),
    [codeLanguage]
  )

  useEffect(() => {
    if (!block.content) return
    if (codeLanguage === 'mermaid') return
    if (!codeLanguage || codeLanguage === '') throttledDetectLanguage(block.content)
    updateCode(block.content, codeLanguage)
  }, [block.content])

  useEffect(() => {
    const normalizedLang = sanitizeLanguage(block.artifact?.language)
    if (normalizedLang === '') {
      throttledDetectLanguage(block.content)
    } else {
      setCodeLanguage(normalizedLang)
    }
  }, [block.artifact?.language])

  useEffect(() => {
    updateCode(block.content, codeLanguage)
  }, [codeLanguage])

  useEffect(() => {
    if (!codeEditorRef.current) return
    createEditor(codeEditorRef.current, block.content, codeLanguage)
    const editor = getEditorView()
    if (editor) editor.updateOptions({ fontFamily: uiSettingsStore.formattedCodeFontFamily })
  }, [])

  useEffect(() => {
    getEditorView()?.updateOptions({ fontFamily: uiSettingsStore.formattedCodeFontFamily })
  }, [uiSettingsStore.formattedCodeFontFamily])

  const handleCopy = async () => {
    try {
      deviceClient.copyText(block.content)
      setCopyText('Copied!')
      setTimeout(() => setCopyText('Copy'), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const previewCode = () => {
    if (!isPreviewable || !messageId || !threadId) return
    const artifactType = codeLanguage === 'html' ? 'text/html' : 'image/svg+xml'
    const artifactTitle = codeLanguage === 'html' ? 'HTML Preview' : 'SVG Preview'
    artifactStore.showArtifact(
      {
        id: `temp-${codeLanguage}-${nanoid()}`,
        type: artifactType,
        title: artifactTitle,
        language: codeLanguage || block.artifact?.language,
        content: block.content,
        status: 'loaded'
      },
      messageId,
      threadId,
      { force: true }
    )
  }

  if (isMermaid) {
    return (
      <pre className={`text-xs p-3 bg-muted rounded-lg overflow-auto ${className ?? ''}`}>
        {block.content}
      </pre>
    )
  }

  return (
    <div
      className={`m-4 rounded-lg border border-border overflow-hidden shadow-sm ${className ?? ''}`}
    >
      <div className="flex justify-between items-center p-2 bg-muted text-xs">
        <span className="flex items-center space-x-2">
          <Icon icon={languageIcon} className="w-4 h-4" />
          <span className="text-gray-600 dark:text-gray-400 font-mono font-bold">
            {displayLanguage}
          </span>
        </span>
        {isPreviewable ? (
          <div className="flex items-center space-x-2">
            <button
              className="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
              onClick={handleCopy}
            >
              {copyText}
            </button>
            <button
              className="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
              onClick={previewCode}
            >
              Preview
            </button>
          </div>
        ) : (
          <button
            className="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
            onClick={handleCopy}
          >
            {copyText}
          </button>
        )}
      </div>
      <div
        ref={codeEditorRef}
        className="min-h-[30px] max-h-[500px] text-xs overflow-auto bg-background font-mono leading-relaxed"
        data-language={codeLanguage}
      />
      <style>{`.cm-editor .cm-content { font-family: var(--dc-code-font-family) !important; }`}</style>
    </div>
  )
}

// src/renderer/src/components/artifacts/CodeArtifact.vue
<template>
  <MermaidBlockNode v-if="isMermaid" :node="mermaidNode" />
  <div v-else class="m-4 rounded-lg border border-border overflow-hidden shadow-sm">
    <div class="flex justify-between items-center p-2 bg-muted text-xs">
      <span class="flex items-center space-x-2">
        <Icon :icon="languageIcon" class="w-4 h-4" />
        <span class="text-gray-600 dark:text-gray-400 font-mono font-bold">{{
          displayLanguage
        }}</span>
      </span>
      <div v-if="isPreviewable" class="flex items-center space-x-2">
        <button
          class="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
          @click="handleCopy"
        >
          {{ copyText }}
        </button>
        <button
          class="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
          @click="previewCode"
        >
          {{ t('artifacts.preview') }}
        </button>
      </div>
      <button
        v-else
        class="text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
        @click="handleCopy"
      >
        {{ copyText }}
      </button>
    </div>
    <div
      ref="codeEditor"
      class="min-h-[30px] max-h-[500px] text-xs overflow-auto bg-background font-mono leading-relaxed"
      :data-language="codeLanguage"
    ></div>
  </div>
</template>
<script setup lang="ts">
import { ref, computed, defineComponent, h, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useThrottleFn } from '@vueuse/core'
import { Icon } from '@iconify/vue'
import { createDeviceClient } from '@api/DeviceClient'
import { useArtifactStore } from '@/stores/artifact'
import { useUiSettingsStore } from '@/stores/uiSettingsStore'
import { detectLanguage, useMonaco } from 'stream-monaco'
import { nanoid } from 'nanoid'

const MermaidBlockNode = defineComponent({
  name: 'MermaidBlockNode',
  props: {
    node: { type: Object, required: true }
  },
  setup(props) {
    return () =>
      h(
        'pre',
        {
          class: 'text-xs p-3 bg-muted rounded-lg overflow-auto'
        },
        props.node.code
      )
  }
})

function getLanguageIcon(language: string): string {
  const icons: Record<string, string> = {
    javascript: 'logos:javascript',
    typescript: 'logos:typescript-icon',
    python: 'logos:python',
    html: 'logos:html-5',
    css: 'logos:css-3',
    json: 'codicon:json',
    markdown: 'codicon:markdown',
    java: 'logos:java',
    cpp: 'logos:c-plusplus',
    csharp: 'logos:c-sharp',
    go: 'logos:go',
    rust: 'logos:rust',
    sql: 'codicon:database',
    shell: 'codicon:terminal',
    yaml: 'codicon:settings',
    xml: 'codicon:code',
    vue: 'logos:vue',
    react: 'logos:react',
    svelte: 'logos:svelte-icon'
  }
  return icons[language] || 'codicon:file-code'
}

const props = defineProps<{
  block: {
    artifact: {
      type: string
      title: string
      language?: string
    }
    content: string
  }
  isPreview: boolean
  messageId?: string
  threadId?: string
}>()

const { t } = useI18n()
const deviceClient = createDeviceClient()
const uiSettingsStore = useUiSettingsStore()
const { createEditor, updateCode, getEditorView } = useMonaco({
  wordWrap: 'on',
  wrappingIndent: 'same',
  fontFamily: uiSettingsStore.formattedCodeFontFamily
})
const artifactStore = useArtifactStore()
const copyText = ref(t('common.copy'))
const codeEditor = ref<HTMLElement>()

const sanitizeLanguage = (language?: string | null) => {
  if (!language) return ''
  const normalized = language.trim().toLowerCase()

  switch (normalized) {
    case 'md':
      return 'markdown'
    case 'plain':
    case 'text':
      return 'plaintext'
    case 'htm':
      return 'html'
    default:
      return normalized
  }
}

const codeLanguage = ref(sanitizeLanguage(props.block.artifact?.language))
const applyFontFamily = (fontFamily: string) => {
  const editor = getEditorView()
  if (editor) {
    editor.updateOptions({ fontFamily })
  }
}

// 创建节流版本的语言检测函数，1秒内最多执行一次
const throttledDetectLanguage = useThrottleFn(
  (code: string) => {
    codeLanguage.value = sanitizeLanguage(detectLanguage(code))
  },
  1000,
  true
)

// Initialize language detection if needed
if (!codeLanguage.value || codeLanguage.value === '') {
  throttledDetectLanguage(props.block.content)
}

// Check if the code block is a Mermaid diagram
const isMermaid = computed(() => codeLanguage.value === 'mermaid')

// Create mermaid node for MermaidBlockNode component
const mermaidNode = computed(() => ({
  type: 'code_block' as const,
  language: 'mermaid',
  code: props.block.content,
  raw: props.block.content
}))

// Check if the language is previewable (HTML or SVG)
const isPreviewable = computed(() => {
  const lang = codeLanguage.value
  return lang === 'html' || lang === 'svg'
})

// 获取语言图标
const languageIcon = computed(() => {
  return getLanguageIcon(codeLanguage.value)
})

// 获取显示用的语言名称
const displayLanguage = computed(() => {
  const lang = codeLanguage.value
  const displayNames: Record<string, string> = {
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    python: 'Python',
    java: 'Java',
    cpp: 'C++',
    csharp: 'C#',
    php: 'PHP',
    ruby: 'Ruby',
    go: 'Go',
    rust: 'Rust',
    swift: 'Swift',
    kotlin: 'Kotlin',
    html: 'HTML',
    css: 'CSS',
    scss: 'SCSS',
    sql: 'SQL',
    json: 'JSON',
    yaml: 'YAML',
    markdown: 'Markdown',
    bash: 'Bash',
    shell: 'Shell',
    powershell: 'PowerShell',
    dockerfile: 'Dockerfile',
    vue: 'Vue',
    react: 'React',
    xml: 'XML',
    svg: 'SVG',
    mermaid: 'Mermaid',
    text: 'Plain Text',
    http: 'HTTP',
    uri: 'URI',
    dos: 'DOS Batch',
    '': 'Plain Text'
  }
  return displayNames[lang] || lang.charAt(0).toUpperCase() + lang.slice(1)
})

const handleCopy = async () => {
  try {
    deviceClient.copyText(props.block.content)
    copyText.value = t('common.copySuccess')
    setTimeout(() => {
      copyText.value = t('common.copy')
    }, 2000)
  } catch (err) {
    console.error('Failed to copy:', err)
  }
}

// 预览HTML/SVG代码
const previewCode = () => {
  if (!isPreviewable.value || !props.messageId || !props.threadId) return

  const lowerLang = codeLanguage.value
  const artifactType = lowerLang === 'html' ? 'text/html' : 'image/svg+xml'
  const artifactTitle =
    lowerLang === 'html'
      ? t('artifacts.htmlPreviewTitle') || 'HTML Preview'
      : t('artifacts.svgPreviewTitle') || 'SVG Preview'

  artifactStore.showArtifact(
    {
      id: `temp-${lowerLang}-${nanoid()}`,
      type: artifactType,
      title: artifactTitle,
      language: lowerLang || props.block.artifact?.language,
      content: props.block.content,
      status: 'loaded'
    },
    props.messageId,
    props.threadId,
    { force: true }
  )
}

// 监听代码变化
watch(
  () => props.block.content,
  (newCode) => {
    if (!newCode) return

    // If it's a mermaid diagram, let MermaidBlockNode handle it
    if (codeLanguage.value === 'mermaid') {
      return
    }

    // Check if we need to detect language
    if (!codeLanguage.value || codeLanguage.value === '') {
      throttledDetectLanguage(newCode)
    }

    updateCode(props.block.content, codeLanguage.value)
  },
  { immediate: true }
)

// 监听语言变化
watch(
  () => props.block.artifact?.language,
  (newLanguage) => {
    const normalizedLang = sanitizeLanguage(newLanguage)
    if (normalizedLang === '') {
      throttledDetectLanguage(props.block.content)
    } else {
      codeLanguage.value = normalizedLang
    }
    // If the language changes, we need to recreate the editor with the new language
  }
)

// 监听计算出的语言变化
watch(
  () => codeLanguage.value,
  () => {
    // If the computed language changes, we need to recreate the editor
    updateCode(props.block.content, codeLanguage.value)
  }
)

// 初始化代码编辑器
onMounted(() => {
  if (!codeEditor.value) return
  createEditor(codeEditor.value, props.block.content, codeLanguage.value)
  applyFontFamily(uiSettingsStore.formattedCodeFontFamily)
})

watch(
  () => uiSettingsStore.formattedCodeFontFamily,
  (font) => {
    applyFontFamily(font)
  }
)
</script>
<style>
/* Ensure CodeMirror inherits the right font in the editor */
.cm-editor .cm-content {
  font-family: var(--dc-code-font-family) !important;
}
</style>
